
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Database
{

using System;
    using System.Collections.Generic;
    
public partial class AspNetUser
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public AspNetUser()
    {

        this.AspNetUserClaims = new HashSet<AspNetUserClaim>();

        this.AspNetUserLogins = new HashSet<AspNetUserLogin>();

        this.MasterBoards = new HashSet<MasterBoard>();

        this.MasterBooks = new HashSet<MasterBook>();

        this.MasterBooks1 = new HashSet<MasterBook>();

        this.MasterCategories = new HashSet<MasterCategory>();

        this.MasterCategories1 = new HashSet<MasterCategory>();

        this.MasterClasses = new HashSet<MasterClass>();

        this.MasterClasses1 = new HashSet<MasterClass>();

        this.MasterSubjects = new HashSet<MasterSubject>();

        this.MyLibraries = new HashSet<MyLibrary>();

        this.MyLibraries1 = new HashSet<MyLibrary>();

        this.Schools = new HashSet<School>();

        this.Schools1 = new HashSet<School>();

        this.UserDetails = new HashSet<UserDetail>();

        this.UserDetails1 = new HashSet<UserDetail>();

        this.UserDetails2 = new HashSet<UserDetail>();

        this.UserExcelDatas = new HashSet<UserExcelData>();

        this.UserExcelDatas1 = new HashSet<UserExcelData>();

        this.UserExcelMetaDatas = new HashSet<UserExcelMetaData>();

        this.UserExcelMetaDatas1 = new HashSet<UserExcelMetaData>();

        this.UserExcelMetaDatas2 = new HashSet<UserExcelMetaData>();

        this.AspNetRoles = new HashSet<AspNetRole>();

        this.UserCarts = new HashSet<UserCart>();

        this.UserCarts1 = new HashSet<UserCart>();

        this.UserCarts2 = new HashSet<UserCart>();

        this.UserCartItems = new HashSet<UserCartItem>();

        this.UserCartItems1 = new HashSet<UserCartItem>();

    }


    public string Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public int Gender { get; set; }

    public Nullable<System.DateTime> DOB { get; set; }

    public string MobNo { get; set; }

    public string EmailId { get; set; }

    public string SecurityQuestion { get; set; }

    public string SecurityAnswer { get; set; }

    public string eUserName { get; set; }

    public string ePassword { get; set; }

    public bool MobValidate { get; set; }

    public bool EmailValidate { get; set; }

    public int LoginMode { get; set; }

    public bool LoginThirdParty { get; set; }

    public int LoginSourse { get; set; }

    public Nullable<System.DateTime> LastLogin { get; set; }

    public string Image { get; set; }

    public Nullable<System.DateTime> dtmCreate { get; set; }

    public Nullable<System.DateTime> dtmUpdate { get; set; }

    public Nullable<System.DateTime> dtmDelete { get; set; }

    public int Status { get; set; }

    public string TimeZone { get; set; }

    public string AccessLevels { get; set; }

    public int DisplayOrder { get; set; }

    public string Email { get; set; }

    public bool EmailConfirmed { get; set; }

    public string PasswordHash { get; set; }

    public string SecurityStamp { get; set; }

    public string PhoneNumber { get; set; }

    public bool PhoneNumberConfirmed { get; set; }

    public bool TwoFactorEnabled { get; set; }

    public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }

    public bool LockoutEnabled { get; set; }

    public int AccessFailedCount { get; set; }

    public string UserName { get; set; }

    public string UserExcelMetaDataId { get; set; }

    public string UniqueId { get; set; }

    public Nullable<int> FromUpload { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MasterBoard> MasterBoards { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MasterBook> MasterBooks { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MasterBook> MasterBooks1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MasterCategory> MasterCategories { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MasterCategory> MasterCategories1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MasterClass> MasterClasses { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MasterClass> MasterClasses1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MasterSubject> MasterSubjects { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MyLibrary> MyLibraries { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MyLibrary> MyLibraries1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<School> Schools { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<School> Schools1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserDetail> UserDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserDetail> UserDetails1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserDetail> UserDetails2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserExcelData> UserExcelDatas { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserExcelData> UserExcelDatas1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserExcelMetaData> UserExcelMetaDatas { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserExcelMetaData> UserExcelMetaDatas1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserExcelMetaData> UserExcelMetaDatas2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AspNetRole> AspNetRoles { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserCart> UserCarts { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserCart> UserCarts1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserCart> UserCarts2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserCartItem> UserCartItems { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserCartItem> UserCartItems1 { get; set; }

}

}
