
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Database
{

using System;
    using System.Collections.Generic;
    
public partial class MasterCategory
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MasterCategory()
    {

        this.MasterBooks = new HashSet<MasterBook>();

        this.MasterCategory1 = new HashSet<MasterCategory>();

    }


    public long Id { get; set; }

    public string Title { get; set; }

    public string PageTitle { get; set; }

    public string MetaDescription { get; set; }

    public string OgTitle { get; set; }

    public string OgDescription { get; set; }

    public string TwitterTitle { get; set; }

    public string TwitterDescription { get; set; }

    public string Author { get; set; }

    public string KeyWords { get; set; }

    public string Description { get; set; }

    public Nullable<long> ParentId { get; set; }

    public string ShortCode { get; set; }

    public Nullable<short> DisplayOrder { get; set; }

    public string Image { get; set; }

    public string BannerImage { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.DateTime> UpdateDate { get; set; }

    public Nullable<byte> Status { get; set; }

    public string IPaddress { get; set; }



    public virtual AspNetUser AspNetUser { get; set; }

    public virtual AspNetUser AspNetUser1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MasterBook> MasterBooks { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MasterCategory> MasterCategory1 { get; set; }

    public virtual MasterCategory MasterCategory2 { get; set; }

}

}
