
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Database
{

using System;
    using System.Collections.Generic;
    
public partial class MasterBook
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MasterBook()
    {

        this.MyLibraries = new HashSet<MyLibrary>();

        this.UserCartItems = new HashSet<UserCartItem>();

    }


    public string Id { get; set; }

    public Nullable<long> MasterCategoryId { get; set; }

    public Nullable<long> MasterClassId { get; set; }

    public Nullable<long> MasterBoardId { get; set; }

    public Nullable<long> MasterSubjectid { get; set; }

    public Nullable<long> MasterSeriesid { get; set; }

    public string Title { get; set; }

    public string Author { get; set; }

    public string ISBN { get; set; }

    public string Edition { get; set; }

    public string Image { get; set; }

    public string Description { get; set; }

    public string PageTitle { get; set; }

    public string MetaDescription { get; set; }

    public string OgTitle { get; set; }

    public string OgDescription { get; set; }

    public string TwitterTitle { get; set; }

    public string TwitterDescription { get; set; }

    public string KeyWords { get; set; }

    public Nullable<long> ParentId { get; set; }

    public string ShortCode { get; set; }

    public Nullable<short> DisplayOrder { get; set; }

    public string BannerImage { get; set; }

    public string ServerId { get; set; }

    public string EncriptionKey { get; set; }

    public string isSize { get; set; }

    public Nullable<decimal> EbookPrice { get; set; }

    public Nullable<decimal> PrintPrice { get; set; }

    public Nullable<decimal> Discount { get; set; }

    public Nullable<int> Colour { get; set; }

    public Nullable<long> EbookSize_MB_ { get; set; }

    public Nullable<int> Ebook { get; set; }

    public Nullable<int> Pbook { get; set; }

    public Nullable<int> Audio { get; set; }

    public Nullable<int> EBookType { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.DateTime> UpdateDate { get; set; }

    public Nullable<byte> Status { get; set; }

    public string IPaddress { get; set; }



    public virtual AspNetUser AspNetUser { get; set; }

    public virtual AspNetUser AspNetUser1 { get; set; }

    public virtual MasterBoard MasterBoard { get; set; }

    public virtual MasterCategory MasterCategory { get; set; }

    public virtual MasterClass MasterClass { get; set; }

    public virtual MasterSery MasterSery { get; set; }

    public virtual MasterSubject MasterSubject { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MyLibrary> MyLibraries { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserCartItem> UserCartItems { get; set; }

}

}
