
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Database
{

using System;
    using System.Collections.Generic;
    
public partial class OrderDetails
{

    public System.Guid Id { get; set; }

    public string OrderId { get; set; }

    public string BookId { get; set; }

    public string Userid { get; set; }

    public string CartId { get; set; }

    public Nullable<int> PaymentStatusId { get; set; }

    public Nullable<System.DateTime> AddedOn { get; set; }

    public Nullable<System.DateTime> UpdatedOn { get; set; }



    public virtual PaymentStatus PaymentStatus { get; set; }

}

}
