
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Database
{

using System;
    using System.Collections.Generic;
    
public partial class PaymentDetails
{

    public System.Guid Id { get; set; }

    public string OrderId { get; set; }

    public Nullable<decimal> PaidAmount { get; set; }

    public string UserId { get; set; }

    public Nullable<long> TrackingId { get; set; }

    public string BankRefNo { get; set; }

    public string OrderStatus { get; set; }

    public string FailureMessage { get; set; }

    public string Mode { get; set; }

    public string CardName { get; set; }

    public string CustomerCardId { get; set; }

    public string StatusCode { get; set; }

    public string StatusMessage { get; set; }

    public Nullable<decimal> DiscountValue { get; set; }

    public string Retry { get; set; }

    public Nullable<int> ResponseCode { get; set; }

    public Nullable<System.DateTime> TransactionDate { get; set; }

    public Nullable<decimal> TransactionFees { get; set; }

}

}
