
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Database
{

using System;
    using System.Collections.Generic;
    
public partial class School
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public School()
    {

        this.UserDetails = new HashSet<UserDetail>();

    }


    public string Id { get; set; }

    public string AspNetUserId { get; set; }

    public Nullable<long> MasterBoardId { get; set; }

    public string Title { get; set; }

    public string SchoolCode { get; set; }

    public Nullable<long> Strength { get; set; }

    public string ITIncharge { get; set; }

    public string EmailId { get; set; }

    public string Logo { get; set; }

    public string ContactNo { get; set; }

    public string AlterNateContactNo { get; set; }

    public string Principle { get; set; }

    public string PrincipleContactNo { get; set; }

    public string AddressLine1 { get; set; }

    public string AddressLine2 { get; set; }

    public string AddressLine3 { get; set; }

    public string State { get; set; }

    public string City { get; set; }

    public string Pincode { get; set; }

    public string Description { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public string IPAddress { get; set; }

    public Nullable<int> Status { get; set; }



    public virtual AspNetUser AspNetUser { get; set; }

    public virtual AspNetUser AspNetUser1 { get; set; }

    public virtual MasterBoard MasterBoard { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserDetail> UserDetails { get; set; }

}

}
