
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Database
{

using System;
    using System.Collections.Generic;
    
public partial class UserDetail
{

    public string UseDetailId { get; set; }

    public string AspNetUserId { get; set; }

    public Nullable<long> MasterClassId { get; set; }

    public Nullable<long> MasterBoardId { get; set; }

    public string AdmissionNo { get; set; }

    public string AccountCode { get; set; }

    public string ParentName { get; set; }

    public Nullable<System.DateTime> DateOfBirth { get; set; }

    public string SchoolId { get; set; }

    public string UserCode { get; set; }

    public string Name { get; set; }

    public string RollNo { get; set; }

    public string Session { get; set; }

    public string ContactNo { get; set; }

    public string Address { get; set; }

    public Nullable<System.DateTime> ExpiyDate { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public string IpAddress { get; set; }



    public virtual AspNetUser AspNetUser { get; set; }

    public virtual AspNetUser AspNetUser1 { get; set; }

    public virtual AspNetUser AspNetUser2 { get; set; }

    public virtual MasterBoard MasterBoard { get; set; }

    public virtual MasterClass MasterClass { get; set; }

    public virtual School School { get; set; }

}

}
