
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Database
{

using System;
    using System.Collections.Generic;
    
public partial class UserCart
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public UserCart()
    {

        this.UserCartItems = new HashSet<UserCartItem>();

    }


    public string Id { get; set; }

    public string AspNetUserId { get; set; }

    public string CartUniqueId { get; set; }

    public Nullable<decimal> Discount { get; set; }

    public Nullable<decimal> Total { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.DateTime> UpdateDate { get; set; }

    public Nullable<byte> Status { get; set; }

    public string IPaddress { get; set; }



    public virtual AspNetUser AspNetUser { get; set; }

    public virtual AspNetUser AspNetUser1 { get; set; }

    public virtual AspNetUser AspNetUser2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserCartItem> UserCartItems { get; set; }

}

}
