
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Database
{

using System;
    using System.Collections.Generic;
    
public partial class UserExcelMetaData
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public UserExcelMetaData()
    {

        this.UserExcelDatas = new HashSet<UserExcelData>();

    }


    public string Id { get; set; }

    public string AspNetUserId { get; set; }

    public string FileName { get; set; }

    public string SheetName { get; set; }

    public string UploadedFileName { get; set; }

    public Nullable<int> Rows { get; set; }

    public Nullable<int> Cols { get; set; }

    public Nullable<int> LoopCount { get; set; }

    public string FileMetaData { get; set; }

    public string Description { get; set; }

    public System.DateTime CreateDate { get; set; }

    public System.DateTime UpdatedDate { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public string IPAddress { get; set; }

    public int Status { get; set; }



    public virtual AspNetUser AspNetUser { get; set; }

    public virtual AspNetUser AspNetUser1 { get; set; }

    public virtual AspNetUser AspNetUser2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserExcelData> UserExcelDatas { get; set; }

}

}
