
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Database
{

using System;
    using System.Collections.Generic;
    
public partial class UserExcelData
{

    public string Id { get; set; }

    public string UserExcelMetaDataId { get; set; }

    public Nullable<long> MasterClassId { get; set; }

    public Nullable<long> MasterBoardId { get; set; }

    public string AspNetUserId { get; set; }

    public string UpdateUserId { get; set; }

    public string AdmissionNo { get; set; }

    public string AccountCode { get; set; }

    public string AccountName { get; set; }

    public string ParentName { get; set; }

    public Nullable<System.DateTime> DateOfBirth { get; set; }

    public string Name { get; set; }

    public string Class { get; set; }

    public string RollNo { get; set; }

    public string Session { get; set; }

    public string Board { get; set; }

    public string Password { get; set; }

    public string NameAbbr { get; set; }

    public string UserCode { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public string IPAddress { get; set; }

    public Nullable<int> Status { get; set; }



    public virtual AspNetUser AspNetUser { get; set; }

    public virtual AspNetUser AspNetUser1 { get; set; }

    public virtual UserExcelMetaData UserExcelMetaData { get; set; }

}

}
